Added python scripts for brownian motion
MiztaOak/Group55_BachelorsThesis pull request #5
Opened 2021-02-10 18:05 UTC by rasmusdurge

2021-02-10 18:05 UTC, l0gren commented
cool

2021-02-10 18:07 UTC, l0gren commented on MathModels/brownianBridge.py
> +seed = 0
idk

2021-02-10 18:08 UTC, MIDO-96 approved these changes
works fine

2021-02-10 18:08 UTC, MiztaOak requested changes
Just for testing

2021-02-11 08:28 UTC, jonnyfre approved these changes
ok

2021-02-15 17:28 UTC, merged